name: CI Build

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

concurrency:
  group: ci-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: "3.9"
  AWS_REGION : "us-east-2"
  TERRAFORM_VERSION : "1.6.2"
  AWS_BUCKET : "terraform-backend-defuse-kit"
  BACKEND_KEY : "state.tfstate"
  SERVICE_NAME : "defuse-kit"
  WORKING_DIR: ./platform

permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout

jobs:
  CI:
    name: "Terraform Plan"
    timeout-minutes: 30
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR }}

    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::814537535901:role/GitHubAction-AssumeRoleWithAction
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: Sts GetCallerIdentity
        run: |
          aws sts get-caller-identity

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
            terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check .
        continue-on-error: true

      - name: Terraform Init
        id: init
        run:
            terraform init
      
      - name: Terraform Plan
        id: plan
        run:
            terraform plan